### ISSUE TITLE
Error: Cannot find module 'extract-text-webpack-plugin'

### ISSUE THREAD

**Issue by nikican** [Lemoncode/react-by-sample#62]
When I follow instructions I get the following error:
`module.js:472
    throw err;
    ^

Error: Cannot find module 'extract-text-webpack-plugin'`

'extract-text-webpack-plugin' is not in the list of plugins in this part of the guide:
`npm install css-loader style-loader file-loader url-loader html-webpack-plugin awesome-typescript-loader --save-dev`

**Comment by brauliodiez** [comment]
Hi @nikican in which sample you get this error?

Thanks

**Comment by nikican** [comment]
Hi @brauliodiez 
Sorry, I should have formulated the issue a bit better.

It happens when I follow instructions for 00 Boilerplate.

In readme.md file there is a line:
`npm install css-loader style-loader file-loader url-loader html-webpack-plugin awesome-typescript-loader --save-dev` 
and 'extract-text-webpack-plugin' is not in that list which causes the above mentioned error.

**Comment by brauliodiez** [comment]
Just updating the readme step to this would fix the issue?

```
npm install css-loader style-loader file-loader url-loader html-webpack-plugin awesome-typescript-loader -extract-text-webpack-plugin --save-dev
```

If you can confirm that's the case, I can update the guide, or if you wish you can fork and do it (as you preffer).

Thanks

**Comment by brauliodiez** [comment]
Hi @nikican, @mjuanfe have just uploaded a fix, merged :-). Thanks for your help.
