### ISSUE TITLE
Change 'var' to 'const' in the Sidebar. Add type to the divStyle

### ISSUE THREAD

**Issue by juanbermudezpareja** [Lemoncode/react-by-sample#66]
4th case. Change 'var' to 'const' in the Sidebar component. Add type to the divStyle

**Comment by juanbermudezpareja** [comment]
I forgot to put the divStyle variable out of the SidebarComponent scope. I am going to change it...

**Comment by juanbermudezpareja** [comment]
It has been moved the divStyle element out of Sidebar component. Issue can be closed

**Comment by ebarriosara** [comment]
I think there are some errors after the last change. To solve them, the chage should be like this:

const divStyle = (props: React.CSSProperties) => ({
      width: (props.isVisible) ? '250px' : '0px'
});

export const SidebarComponent = (props: Props) => {
 return (
   <div id="mySidenav" className={classNames.sidenav} style={divStyle(props)}>
       <span>Basic side bar, first steps</span>
   </div>
 );
}

**Comment by juanbermudezpareja** [comment]
Ok, thanks @ebarriosara
