### ISSUE TITLE
Update 01 to use typescript + babel

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/react-by-sample#78]
00 is already ported, update 01 and other samples if possible

Right now is using only Typescript, we want two steps (useBabel plus .babelrc), check 

https://github.com/Lemoncode/from-react-to-redux-ts/tree/master/00%20Boilerplate

Sample 00 Boilerplate

Propagate update to rest of files.

**Comment by torres007** [comment]
In progress...

**Comment by torres007** [comment]
PR submitted.
